### ISSUE TITLE
How to validate on raw datas(CRVD)?

### ISSUE THREAD

**Issue by wx5391805** [ChenyangQiQi/BSVD#1]
I see quantitative comparisons of PSNR and SSIM on the CRVD test set for raw image denosing. How can we test this ? Thank you~

**Comment by ChenyangQiQi** [comment]
Sorry, I am still cleaning the code for CRVD. Please wait.

**Comment by wx5391805** [comment]
Thanks, looking forward to it

**Comment by oneTaken** [comment]
Half year is passed, so is there anything update?

**Comment by ChenyangQiQi** [comment]
Hi, Thanks for your interest. I will have some time between March 16 and 24.
And I will update the code for CRVD in those days.

**Comment by ChenyangQiQi** [comment]
Hi, @wx5391805 , @oneTaken . I have updated a [branch](https://github.com/ChenyangQiQi/BSVD/tree/bsvd_raw) of code for denoising on CRVD test set.
The code directory is still quite dirty. You may look into the command in [README](https://github.com/ChenyangQiQi/BSVD/tree/bsvd_raw) if you would like to.
