### ISSUE TITLE
Log Files from Training

### ISSUE THREAD

**Issue by gauenk** [ChenyangQiQi/BSVD#2]
Thank you for your awesome code!

I am hoping you might open-source the log files you have from training. Maybe the training and validation loss as a function of epoch (and/or batch) with an estimate of the runtime?

**Comment by ChenyangQiQi** [comment]
Thanks for your interest.
Here is the log and tensorboard of our training
https://hkustconnect-my.sharepoint.com/:f:/g/personal/cqiaa_connect_ust_hk/EqonQBPy6LZBm3nCsOGRd1EBsO3CgEMpRKoCnNH6YDof7w?e=197o0V

**Comment by gauenk** [comment]
Thank you for the information!
