### ISSUE TITLE
Question about Bidirectional Buffer Block

### ISSUE THREAD

**Issue by haikunzhang95** [ChenyangQiQi/BSVD#4]
you said in the paper： For time step 𝑖 < 𝑁, each input frame activates one deeper Bidirectional Buffer Block 𝐵0,𝑖 in our network. Therefore, when the first denoised frame 𝑦0 comes out, there are already 𝑁 + 1 frames fed into our inference block. 

What is the number of Bidirectional Buffer Block's? 16？

Why can a frame of input also produce output when I test it?

Thank you very much！

**Comment by ChenyangQiQi** [comment]
Thanks for your interest!
Yes, the number of Bidirectional Buffer Block is 16.
If you run our test yaml (https://github.com/ChenyangQiQi/BSVD/blob/main/options/test/bsvd_c64.yml),

At first, empty tensor is appended during the first N inputs (https://github.com/ChenyangQiQi/BSVD/blob/720de1b4ff20870f72d0d2c6c9cdc80030b99df5/Experimental_root/archs/bsvd_arch.py#L526). 
Then, dummy tensor will keep feeding in until the end of inference
(https://github.com/ChenyangQiQi/BSVD/blob/720de1b4ff20870f72d0d2c6c9cdc80030b99df5/Experimental_root/archs/bsvd_arch.py#L538)
Finally these empty tensor at the beginning steps are trimmed (https://github.com/ChenyangQiQi/BSVD/blob/720de1b4ff20870f72d0d2c6c9cdc80030b99df5/Experimental_root/archs/bsvd_arch.py#L550)
