### ISSUE TITLE
Uni-directional model

### ISSUE THREAD

**Issue by kleMor** [ChenyangQiQi/BSVD#5]
Hello,

Is it possible to provide the uni-directional pre-trained model?

Best regards

**Comment by kleMor** [comment]
I am looking for an upper bound reference for a causal model.

Thanks

**Comment by ChenyangQiQi** [comment]
Thanks for your interest. This link contains the checkpoint and path for the uni_directional model.
https://hkustconnect-my.sharepoint.com/:f:/g/personal/cqiaa_connect_ust_hk/EtJVxVxBDSBDv5qOvRfM9xcBjkpPLbl4sfhBzpIPAWVMiw?e=cTNO8r

**Comment by kleMor** [comment]
Hi,

I appreciate your response!!!

Thank you very much!
