### ISSUE TITLE
Request for a checkpoint without noise_map for blind video test

### ISSUE THREAD

**Issue by lixingwen2007** [ChenyangQiQi/BSVD#6]
Hi,
Thank you so much for a great job.It really help me a lot!
I want to do some learning based on your code，and try to test some videos with nature noise.I see you have tested:Blind denoising on DAVIS and Set8 datasets in your paper.
![image](https://user-images.githubusercontent.com/92158110/220077307-26300d68-a35d-4639-bdc6-18292cd2c981.png)

Can you help send a link of a checkpoint without noise map input?
Thank you very much!

**Comment by ChenyangQiQi** [comment]
Thanks for your interest. 
You may check this for the checkpoint and test log for blind denoising.

https://hkustconnect-my.sharepoint.com/:f:/g/personal/cqiaa_connect_ust_hk/EkmrwTvtKYlLha2G1-8XIskBfYZF2WsUiE8NE5TliWfAoQ?e=bgndf1

**Comment by lixingwen2007** [comment]
Thank you very much！
